pipeline {
    agent {
        docker {
            image 'maven:3.9.9-eclipse-temurin-11'
            args '-v /root/.m2:/root/.m2'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'feature/initial-app',
                    url: 'https://github.com/sunath2711/ci-cd-springboot'
            }
        }

        stage('Build & Test') {
            steps {
                dir('app') {
                    sh 'mvn clean test'
                }
            }
        }
    }
}
